
### Search for movie / series
GET http://www.omdbapi.com/?apikey=9931b7c&s=last

### Search for individual details by imdb id
GET http://www.omdbapi.com/?apikey=9931b7c&i=tt0232500&plot=full

### GET Evry Season
GET http://www.omdbapi.com/?apikey=9931b7c&i=tt1475582&type=episode&plot=full



### GET All episodes by Season
GET http://www.omdbapi.com/?apikey=9931b7c&i=tt0944947&Season=1

###
POST https://json-server-in.vercel.app/api/posts

{
"title": "json-server sample",
"author": "typicode"
}